# Generated by Django 5.0.6 on 2024-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_logo', models.ImageField(upload_to='images/')),
                ('auction_name', models.CharField(max_length=100, unique=True)),
                ('auction_date', models.DateTimeField()),
                ('auction_type', models.CharField(choices=[('Cricket', 'Cricket'), ('VolleyBall', 'VolleyBall'), ('FootBall', 'FootBall'), ('Hockey', 'Hockey')], default='Cricket', max_length=20)),
                ('auction_purse', models.IntegerField()),
                ('min_bid', models.IntegerField()),
                ('bid_increase', models.IntegerField()),
                ('players_per_team', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
