# Generated by Django 5.0.7 on 2024-08-04 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_logo', models.ImageField(blank=True, null=True, upload_to='auction/images/')),
                ('auction_name', models.CharField(max_length=100, unique=True)),
                ('auction_date', models.DateTimeField()),
                ('auction_type', models.CharField(choices=[('Cricket', 'Cricket'), ('VolleyBall', 'VolleyBall'), ('FootBall', 'FootBall'), ('Hockey', 'Hockey')], default='Cricket', max_length=20)),
                ('auction_purse', models.IntegerField()),
                ('min_bid', models.IntegerField()),
                ('bid_increase', models.IntegerField()),
                ('players_per_team', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='player/images/')),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('player_type', models.CharField(choices=[('All Rounder', 'All Rounder'), ('Batsman', 'Batsman'), ('Bowler', 'Bowler')], default='Batsman', max_length=20)),
                ('origin', models.CharField(choices=[('Indian', 'Indian'), ('Overseas', 'Overseas')], default='Indian', max_length=20)),
                ('base_price', models.IntegerField()),
                ('player_points', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction')),
            ],
        ),
        migrations.CreateModel(
            name='AddSponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponser_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sponser_logo', models.ImageField(blank=True, null=True, upload_to='sponsers/images/')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction')),
            ],
        ),
        migrations.CreateModel(
            name='AddTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_username', models.CharField(max_length=100)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='teams/images/')),
                ('team_name', models.CharField(max_length=30)),
                ('purse_amt', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sold', 'Sold'), ('unsold', 'Unsold')], default='unsold', max_length=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addplayer')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.addteam')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctions', models.ManyToManyField(to='api.addauction')),
                ('players', models.ManyToManyField(to='api.addplayer')),
                ('sponsers', models.ManyToManyField(to='api.addsponsers')),
                ('teams', models.ManyToManyField(to='api.addteam')),
            ],
        ),
    ]
