# Generated by Django 5.0.6 on 2024-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_image', models.ImageField(upload_to='images/')),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('auction_type', models.CharField(choices=[('Cricket', 'Cricket'), ('VolleyBall', 'VolleyBall'), ('FootBall', 'FootBall'), ('Hockey', 'Hockey')], default='Cricket', max_length=20)),
                ('origin', models.CharField(choices=[('Indian', 'Indian'), ('Overseas', 'Overseas')], default='Indian', max_length=20)),
                ('base_price', models.IntegerField()),
                ('player_points', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_logo', models.ImageField(upload_to='images/')),
                ('team_name', models.CharField(max_length=30)),
                ('team_username', models.CharField(max_length=30)),
                ('purse_amt', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
