# Generated by Django 5.0.6 on 2024-06-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dashboard_sponsers_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplayer',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='addteam',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sponsers',
            name='sponser_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
