# Generated by Django 5.0.6 on 2024-06-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_addplayer_player_image_alter_addteam_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplayer',
            name='auction_type',
            field=models.CharField(choices=[('All Rounder', 'All Rounder'), ('Batsman', 'Batsman'), ('Bowler', 'Bowler')], default='Batsman', max_length=20),
        ),
    ]
