# Generated by Django 5.0.6 on 2024-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_addsponsers_delete_sponsers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='auctions',
            field=models.ManyToManyField(to='api.addauction'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='players',
            field=models.ManyToManyField(to='api.addplayer'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sponsers',
            field=models.ManyToManyField(to='api.addsponsers'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='teams',
            field=models.ManyToManyField(to='api.addteam'),
        ),
    ]
