# Generated by Django 5.0.6 on 2024-07-14 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auctionresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='sponsers',
        ),
        migrations.AddField(
            model_name='addauction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addplayer',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
        migrations.AddField(
            model_name='addteam',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
        migrations.AlterField(
            model_name='addteam',
            name='team_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='addteam',
            name='team_username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='auctionresult',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
        migrations.CreateModel(
            name='AddSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sponsor_logo', models.ImageField(blank=True, null=True, upload_to='sponsors/images/')),
                ('auction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.addauction')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='sponsors',
            field=models.ManyToManyField(to='api.addsponsor'),
        ),
        migrations.DeleteModel(
            name='AddSponsers',
        ),
    ]
