# Generated by Django 5.0.6 on 2024-07-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_dashboard_sponsers_addauction_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='addauction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addplayer',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
        migrations.AlterField(
            model_name='addsponsor',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
        migrations.AlterField(
            model_name='addteam',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
        migrations.AlterField(
            model_name='auctionresult',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
    ]
