# Generated by Django 5.0.6 on 2024-07-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_addsponsers_remove_dashboard_sponsors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionresult',
            name='auction',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
    ]
