# Generated by Django 5.0.6 on 2024-07-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_auctionresult_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionresult',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addauction'),
        ),
    ]
